# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8644ec01c54d28e30b08a7f05b113238d4abf6b6523d0d1f78086689d141b1ac6cb21bc876cf3db726158e190b3f774e56a74514cb590533788087908566769b

test:
  secret_key_base: 748feda87f273d53f50c041b6a3697a87fbb266ce007c9d1c1e9bc74c8c722403845fcba02647ebe0a1befd01208a5f06821b7396c858c6813195a09a37ff9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
